/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Person
DROP CONSTRAINT FK_Person_Oid
GO
ALTER TABLE dbo.Party SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_Person
(
Oid uniqueidentifier NOT NULL ROWGUIDCOL,
FirstName nvarchar(100) NULL,
LastName nvarchar(100) NULL,
MiddleName nvarchar(100) NULL,
Birthday datetime NULL,
Email nvarchar(255) NULL,
MarcaCasino bit NULL
)　ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_Person SET (LOCK_ESCALATION = TABLE)
GO
IF EXISTS(SELECT * FROM dbo.Person)
EXEC('INSERT INTO dbo.Tmp_Person (Oid, FirstName, LastName, MiddleName, Birthday, Email)
SELECT Oid, FirstName, LastName, MiddleName, Birthday, Email FROM dbo.Person WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.Empleado
DROP CONSTRAINT FK_Empleado_Oid
GO
DROP TABLE dbo.Person
GO
EXECUTE sp_rename N'dbo.Tmp_Person', N'Person', 'OBJECT' 
GO
ALTER TABLE dbo.Person ADD CONSTRAINT
PK_Person PRIMARY KEY CLUSTERED 
(
Oid
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Person WITH NOCHECK ADD CONSTRAINT
FK_Person_Oid FOREIGN KEY
(
Oid
) REFERENCES dbo.Party
(
Oid
) ON UPDATE　NO ACTION 
ON DELETE　NO ACTION 
NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Empleado WITH NOCHECK ADD CONSTRAINT
FK_Empleado_Oid FOREIGN KEY
(
Oid
) REFERENCES dbo.Person
(
Oid
) ON UPDATE　NO ACTION 
ON DELETE　NO ACTION 
NOT FOR REPLICATION

GO
ALTER TABLE dbo.Empleado SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
